### ISSUE TITLE
Frontend - Design Home Page

### ISSUE THREAD

**Issue by ttlarson7** [OSU-App-Club/beavsAI-frontend#2]
### Possible Questions:
Q: What is a Frontend? 
A: The front end of a website is everything the user either sees or interacts with when they visit the website. It is responsible for the total look and feel of an online experience. More info: [Frontend (In a website)](https://airfocus.com/glossary/what-is-a-front-end/), [Frontend vs Backend Differences](https://www.freecodecamp.org/news/frontend-vs-backend-whats-the-difference/#feintro)

### Resources:
- UI Inspiration - [StaticHunt](https://statichunt.com), [Dribble](https://dribbble.com/shots/popular)

**Comment by Chchimdi** [comment]
We can use this to know the features the app should have.

Examples:

1. As a user, I want to be able to share my search so that my friends can access what I searched.

2. As a user, I want to be able to delete a chat thread so that it will not be in my search history.
